"""Read Mio's existing GUI session and autonomous-cycle health through ONE.

The health job never logs in or changes services. The separate resume job
reuses only the existing Mio-specific cached-account Continue-as control.
Neither job reads messages, makes model decisions, or sends replies. The existing Mio/Oursong cycle is observed separately from
session authentication; an authenticated browser does not prove autonomous DM.
"""
from __future__ import annotations

from datetime import datetime, timezone
import json
import os
import signal
from pathlib import Path
import subprocess
from typing import Any, Mapping

from agent_core.executor_job_contract import validate_executor_job
from agentos_node.executor_job_adapter import DEFAULT_PROVIDERS, ExecutorJobProviderRegistry
from agentos_node.social.persona_dm import binding_for

JOB_TYPE = "persona.mio.dm.health"
RESUME_JOB_TYPE = "persona.mio.dm.resume"
PROVIDER_ID = "oracle-mio-dm-health-v1"
RESUME_PROVIDER_ID = "oracle-mio-dm-safe-resume-v1"
EXECUTOR_CLASS = "oracle-gui-worker"
EXPECTED_HOME = Path("/home/ubuntu")
CYCLE_RECEIPTS = EXPECTED_HOME / "agent-data/runtime/social/persona/sunlake-milkcat/dm-receipts"
SESSION_STATES = {"AUTHENTICATED", "LOGIN_REQUIRED", "BLOCKED", "UNKNOWN"}
UNIT_STATES = {"active", "inactive", "failed", "activating", "deactivating", "reloading", "unknown"}
CYCLE_STATES = {"DEGRADED", "AUTH_REQUIRED", "ALIVE_IDLE", "PASS_NO_ACTION", "PASS_NO_REPLY", "PASS_REPLY"}


def _base(classification: str, *, available: bool = True, authorized: bool = True) -> dict[str, Any]:
    return {
        "verdict": "FAIL", "classification": classification,
        "executor_available": available, "routable": available,
        "authorized": authorized, "successful": False,
        "credential_exposed": False,
        "dm_session_state": "UNKNOWN",
        "dm_account_state": "UNKNOWN",
        "dm_checked_at": datetime.now(timezone.utc).isoformat(),
    }


def _unit_state(unit: str) -> str:
    try:
        p = subprocess.run(
            ["systemctl", "--user", "is-active", unit],
            stdin=subprocess.DEVNULL, capture_output=True, text=True,
            check=False, timeout=5,
        )
        value = p.stdout.strip()
        return value if value in UNIT_STATES else "unknown"
    except (OSError, subprocess.TimeoutExpired):
        return "unknown"


def _timer_enabled() -> bool | None:
    try:
        p = subprocess.run(
            ["systemctl", "--user", "is-enabled", "mio-oursong-dm-autonomous.timer"],
            stdin=subprocess.DEVNULL, capture_output=True, text=True,
            check=False, timeout=5,
        )
        value = p.stdout.strip()
        if value == "enabled":
            return True
        if value in {"disabled", "masked", "not-found"}:
            return False
    except (OSError, subprocess.TimeoutExpired):
        pass
    return None


def _cycle_health(root: Path = CYCLE_RECEIPTS) -> dict[str, Any]:
    """Project only enum/age fields; never return peer, reason, text or IDs."""
    result: dict[str, Any] = {
        "dm_oursong_cycle_status": "UNKNOWN",
        "dm_oursong_cycle_age_seconds": None,
        "dm_oursong_cycle_fresh": False,
    }
    try:
        # Names are UTC timestamps, generated by the existing cycle writer.
        files = sorted(root.glob("*.json"), reverse=True)
        if not files:
            return result
        latest = files[0]
        if latest.is_symlink() or latest.stat().st_size > 65536:
            return result
        raw = json.loads(latest.read_text(encoding="utf-8"))
        if not isinstance(raw, dict) or raw.get("schema") != "agentos.mio-dm-cycle-receipt/v1":
            return result
        stamp = datetime.fromisoformat(str(raw.get("created_at") or "").replace("Z", "+00:00"))
        if stamp.tzinfo is None:
            return result
        age = int((datetime.now(timezone.utc) - stamp).total_seconds())
        if age < 0 or raw.get("status") not in CYCLE_STATES:
            return result
        result.update({
            "dm_oursong_cycle_status": raw["status"],
            "dm_oursong_cycle_age_seconds": age,
            "dm_oursong_cycle_fresh": age <= 900,
        })
    except (OSError, ValueError, TypeError):
        pass
    return result


def _session_from_markers(stdout: str) -> str:
    markers: dict[str, list[str]] = {}
    for line in stdout.splitlines():
        key, sep, value = line.partition("=")
        if sep and key.startswith("threads_web_dm_login_"):
            markers.setdefault(key, []).append(value)
    if markers.get("threads_web_dm_login_probe") != ["PASS"]:
        return "UNKNOWN"
    if markers.get("threads_web_dm_login_mode") != ["oracle_gui_worker"]:
        return "UNKNOWN"
    states = markers.get("threads_web_dm_login_session_state") or []
    return states[0] if len(states) == 1 and states[0] in SESSION_STATES else "UNKNOWN"


def run_mio_dm_health(request: Mapping[str, Any], *, runtime_root: Path | None = None) -> dict[str, Any]:
    spec = validate_executor_job(request)
    if spec.job_type != JOB_TYPE or spec.executor_class != EXECUTOR_CLASS:
        return _base("MIO_DM_HEALTH_CONTRACT_MISMATCH", available=False, authorized=False)
    if Path.home() != EXPECTED_HOME or os.environ.get("USER") not in (None, "", "ubuntu"):
        return _base("MIO_DM_HEALTH_IDENTITY_MISMATCH", available=False, authorized=False)
    if binding_for("mio").cdp_url != "http://127.0.0.1:9224":
        return _base("MIO_DM_HEALTH_BINDING_MISMATCH", available=False, authorized=False)
    root = runtime_root if runtime_root is not None else Path(__file__).resolve().parents[1]
    probe = root / "scripts/probe_threads_web_dm_login_user.sh"
    if not probe.is_file() or probe.is_symlink():
        return _base("MIO_DM_HEALTH_PROBE_UNAVAILABLE", available=False)
    result = _base("MIO_DM_SESSION_UNKNOWN")
    result.update(_cycle_health())
    result.update({
        "dm_oursong_timer_state": _unit_state("mio-oursong-dm-autonomous.timer"),
        "dm_oursong_timer_enabled": _timer_enabled(),
        "dm_supervisor_timer_state": _unit_state("mio-threads-session-supervisor.timer"),
    })
    try:
        p = subprocess.Popen(
            ["/bin/bash", str(probe)], cwd=str(root),
            stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, text=True, start_new_session=True,
            env={**os.environ, "HOME": str(EXPECTED_HOME), "USER": "ubuntu"},
        )
    except OSError:
        result["classification"] = "MIO_DM_SESSION_PROBE_LAUNCH_FAILED"
        return result
    try:
        stdout, _ = p.communicate(timeout=90)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(p.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        p.communicate()
        result["classification"] = "MIO_DM_SESSION_PROBE_TIMEOUT"
        return result
    if p.returncode != 0:
        result["classification"] = "MIO_DM_SESSION_PROBE_FAILED"
        return result
    state = _session_from_markers(stdout or "")
    account_rows = [line.partition("=")[2] for line in (stdout or "").splitlines()
                    if line.startswith("threads_web_dm_login_account_state=")]
    account = account_rows[0] if len(account_rows) == 1 and account_rows[0] in {
        "EXPECTED", "MISMATCH", "AMBIGUOUS", "UNKNOWN"} else "UNKNOWN"
    result["dm_session_state"] = state
    result["dm_account_state"] = account
    result["classification"] = "MIO_DM_SESSION_" + state
    result["dm_checked_at"] = datetime.now(timezone.utc).isoformat()
    if state == "AUTHENTICATED" and account == "EXPECTED":
        result.update(verdict="PASS", successful=True)
    elif state == "AUTHENTICATED":
        result["classification"] = "MIO_DM_ACCOUNT_" + account
    return result


def register_mio_dm_health_provider(*, registry: ExecutorJobProviderRegistry = DEFAULT_PROVIDERS) -> bool:
    for job, provider, handler in (
        (JOB_TYPE, PROVIDER_ID, run_mio_dm_health),
        (RESUME_JOB_TYPE, RESUME_PROVIDER_ID, run_mio_dm_resume),
    ):
        existing = registry.get(job)
        if existing is not None:
            if existing.provider_id != provider or existing.executor_class != EXECUTOR_CLASS:
                raise RuntimeError("Mio DM provider already registered differently")
        else:
            registry.register(job_type=job, provider_id=provider,
                              executor_class=EXECUTOR_CLASS, handler=handler)
    return True


def run_mio_dm_resume(request: Mapping[str, Any], *, runtime_root: Path | None = None) -> dict[str, Any]:
    """Use only an existing account-specific Continue-as control, then verify.

    No credentials, MFA, human challenge, account switch, DM decision/send, or
    service restart is performed. The existing resume script returns a bounded
    HUMAN_REQUIRED reason if no matching cached-account control is available.
    """
    spec = validate_executor_job(request)
    if spec.job_type != RESUME_JOB_TYPE or spec.executor_class != EXECUTOR_CLASS:
        return _base("MIO_DM_RESUME_CONTRACT_MISMATCH", available=False, authorized=False)
    if Path.home() != EXPECTED_HOME or os.environ.get("USER") not in (None, "", "ubuntu"):
        return _base("MIO_DM_RESUME_IDENTITY_MISMATCH", available=False, authorized=False)
    if binding_for("mio").cdp_url != "http://127.0.0.1:9224":
        return _base("MIO_DM_RESUME_BINDING_MISMATCH", available=False, authorized=False)
    root = runtime_root if runtime_root is not None else Path(__file__).resolve().parents[1]
    script = root / "scripts/resume_threads_persona_login_user.sh"
    gui_bin = EXPECTED_HOME / ".local/share/agentos/gui-worker/venv/bin"
    if not script.is_file() or script.is_symlink() or not os.access(gui_bin / "python3", os.X_OK):
        return _base("MIO_DM_RESUME_RUNTIME_UNAVAILABLE", available=False)
    result = _base("MIO_DM_RESUME_FAILED")
    result["dm_resume_state"] = "FAILED"
    try:
        p = subprocess.Popen(
            ["/bin/bash", str(script)], cwd=str(root),
            stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, text=True, start_new_session=True,
            env={**os.environ, "HOME":str(EXPECTED_HOME), "USER":"ubuntu",
                 "AGENTOS_DM_PERSONA":"mio",
                 "PATH":str(gui_bin) + ":" + os.environ.get("PATH", "/usr/local/bin:/usr/bin:/bin")},
        )
    except OSError:
        result["classification"] = "MIO_DM_RESUME_LAUNCH_FAILED"
        return result
    try:
        stdout, _ = p.communicate(timeout=60)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(p.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        p.communicate()
        result["classification"] = "MIO_DM_RESUME_TIMEOUT"
        return result
    values: dict[str, list[str]] = {}
    for line in (stdout or "").splitlines():
        key, sep, value = line.partition("=")
        if sep and key.startswith("threads_persona_login_resume"):
            values.setdefault(key, []).append(value)
    marker = values.get("threads_persona_login_resume")
    if p.returncode == 0 and marker == ["HUMAN_REQUIRED"]:
        reasons = values.get("threads_persona_login_resume_reason") or []
        reason = reasons[0] if len(reasons) == 1 and reasons[0] in {
            "ACCOUNT_HINT_MISSING", "RESUME_CONTROL_MISSING", "RESUME_DID_NOT_AUTHENTICATE"} else "UNKNOWN"
        result.update(classification="MIO_DM_RESUME_HUMAN_REQUIRED",
                      dm_resume_state="HUMAN_REQUIRED", dm_resume_reason=reason)
        return result
    if p.returncode != 0 or marker != ["PASS"]:
        return result
    # PASS from navigation alone is insufficient: recheck Mio identity and DM.
    from agent_core.executor_job_contract import canonical_executor_job_request
    verified = run_mio_dm_health(canonical_executor_job_request(JOB_TYPE), runtime_root=root)
    recovered = verified.get("successful") is True
    return {**verified, "classification":"MIO_DM_RESUME_RECOVERED" if recovered else "MIO_DM_RESUME_VERIFY_FAILED",
            "dm_resume_state":"RECOVERED" if recovered else "FAILED"}
