/* LayoutLib Browser Adapter v0.3.0
 * Library-side deterministic raster -> anchored Spatial IR implementation.
 * Coordinates are always source-image pixels <-> world meters through coordinate_frame.
 */
(function(global){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function runs(bits,minLen){const out=[];let s=null;for(let i=0;i<=bits.length;i++){const on=i<bits.length?bits[i]:false;if(on&&s===null)s=i;else if(!on&&s!==null){if(i-s>=minLen)out.push([s,i-1]);s=null}}return out}
function overlap(a0,a1,b0,b1){const inter=Math.max(0,Math.min(a1,b1)-Math.max(a0,b0)+1),den=Math.max(1,Math.min(a1-a0+1,b1-b0+1));return inter/den}
function collapse(cands,maxT){const used=new Array(cands.length).fill(false),out=[];for(let i=0;i<cands.length;i++){if(used[i])continue;const seed=cands[i],group=[seed];used[i]=true;let changed=true;while(changed){changed=false;const coords=group.map(g=>g.coord),lo=Math.min(...coords),hi=Math.max(...coords),ga=Math.min(...group.map(g=>g.a)),gb=Math.max(...group.map(g=>g.b));for(let j=0;j<cands.length;j++){const c=cands[j];if(used[j]||c.axis!==seed.axis)continue;if(c.coord<lo-1||c.coord>hi+1)continue;if(Math.max(hi,c.coord)-Math.min(lo,c.coord)+1>maxT)continue;if(overlap(ga,gb,c.a,c.b)>=.72){group.push(c);used[j]=true;changed=true}}}const coords=group.map(g=>g.coord);out.push({axis:seed.axis,coord:coords.reduce((a,b)=>a+b,0)/coords.length,a:Math.min(...group.map(g=>g.a)),b:Math.max(...group.map(g=>g.b)),thick:new Set(coords).size})}return out}
function normalizeRegion(region,w,h){if(!region)return{x:0,y:0,width:w,height:h};const x=clamp(Math.round(region.x),0,w-1),y=clamp(Math.round(region.y),0,h-1);return{x,y,width:Math.max(1,Math.min(Math.round(region.width),w-x)),height:Math.max(1,Math.min(Math.round(region.height),h-y))}}
function makeFrame(region,mpp){return{anchor_px:{x:region.x,y:region.y},anchor_world_m:{x:0,y:0},meters_per_pixel:mpp,rotation_deg:0,image_y_axis:'down'}}
function sourcePxToWorld(frame,p){const a=(frame.rotation_deg||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),dx=(p.x-frame.anchor_px.x)*frame.meters_per_pixel,dy=(p.y-frame.anchor_px.y)*frame.meters_per_pixel*(frame.image_y_axis==='up'?-1:1);return{x:frame.anchor_world_m.x+dx*ca-dy*sa,y:frame.anchor_world_m.y+dx*sa+dy*ca}}
function worldToSourcePx(frame,p){let dx=p.x-frame.anchor_world_m.x,dy=p.y-frame.anchor_world_m.y,a=-(frame.rotation_deg||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),rx=dx*ca-dy*sa,ry=dx*sa+dy*ca;if(frame.image_y_axis==='up')ry=-ry;return{x:frame.anchor_px.x+rx/frame.meters_per_pixel,y:frame.anchor_px.y+ry/frame.meters_per_pixel}}
function analyzeImageData(imageData,opts={}){const W=imageData.width,H=imageData.height,mpp=Number(opts.meters_per_pixel||.02);if(!(mpp>0))throw new Error('meters_per_pixel 必須 > 0');const threshold=clamp(Number(opts.threshold??128),0,255),minLen=clamp(Number(opts.min_wall_length_px||16),2,5000),maxT=clamp(Number(opts.max_wall_thickness_px||16),1,128),height=Number(opts.wall_height_m||2.7),defaultThickness=Number(opts.default_thickness_m||.12),region=normalizeRegion(opts.analysis_region_px,W,H),frame=makeFrame(region,mpp),dark=Array.from({length:region.height},()=>new Uint8Array(region.width)),data=imageData.data;for(let y=0;y<region.height;y++)for(let x=0;x<region.width;x++){const sx=region.x+x,sy=region.y+y,i=(sy*W+sx)*4,gray=Math.round(.299*data[i]+.587*data[i+1]+.114*data[i+2]);dark[y][x]=gray<=threshold?1:0}const c=[];for(let y=0;y<region.height;y++)for(const[a,b]of runs(Array.from(dark[y],Boolean),minLen))c.push({axis:'h',coord:y,a,b});for(let x=0;x<region.width;x++){const col=new Array(region.height);for(let y=0;y<region.height;y++)col[y]=!!dark[y][x];for(const[a,b]of runs(col,minLen))c.push({axis:'v',coord:x,a,b})}const segs=collapse(c,maxT),walls=segs.map((r,n)=>{const sPx=r.axis==='h'?{x:region.x+r.a,y:region.y+r.coord}:{x:region.x+r.coord,y:region.y+r.a},ePx=r.axis==='h'?{x:region.x+r.b,y:region.y+r.coord}:{x:region.x+r.coord,y:region.y+r.b};return{id:`wall-${String(n+1).padStart(4,'0')}`,start:sourcePxToWorld(frame,sPx),end:sourcePxToWorld(frame,ePx),thickness:r.thick>1?r.thick*mpp:defaultThickness,height,confidence:1,source:'auto'}});return{version:'0.3',units:'m',image_width_px:W,image_height_px:H,meters_per_pixel:mpp,coordinate_frame:frame,analysis_region_px:region,threshold,min_wall_length_px:minLen,walls,_debug:{dark}}}
function stripDebug(ir){const c=JSON.parse(JSON.stringify(ir));delete c._debug;return c}
function assertRoundTrip(ir,epsilon=1e-6){for(const w of ir.walls)for(const p of [w.start,w.end]){const px=worldToSourcePx(ir.coordinate_frame,p),p2=sourcePxToWorld(ir.coordinate_frame,px);if(Math.abs(p.x-p2.x)>epsilon||Math.abs(p.y-p2.y)>epsilon)throw new Error('coordinate frame round-trip invariant failed')}return true}
global.LayoutLibBrowser={version:'0.3.0',analyzeImageData,sourcePxToWorld,worldToSourcePx,stripDebug,assertRoundTrip};
})(window);
