/* LayoutLib Browser Adapter v0.5.0
 * Unified raster -> editable Spatial IR. Geometry defaults, manual wall edits,
 * scale calibration and source/world transforms live in the library.
 */
(function(global){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), clone=v=>JSON.parse(JSON.stringify(v));
function runs(bits,minLen){const out=[];let s=null;for(let i=0;i<=bits.length;i++){const on=i<bits.length?bits[i]:false;if(on&&s===null)s=i;else if(!on&&s!==null){if(i-s>=minLen)out.push([s,i-1]);s=null}}return out}
function overlap(a0,a1,b0,b1){const inter=Math.max(0,Math.min(a1,b1)-Math.max(a0,b0)+1),den=Math.max(1,Math.min(a1-a0+1,b1-b0+1));return inter/den}
function collapse(cands,maxT){const used=new Array(cands.length).fill(false),out=[];for(let i=0;i<cands.length;i++){if(used[i])continue;const seed=cands[i],g=[seed];used[i]=true;let changed=true;while(changed){changed=false;const cs=g.map(x=>x.coord),lo=Math.min(...cs),hi=Math.max(...cs),ga=Math.min(...g.map(x=>x.a)),gb=Math.max(...g.map(x=>x.b));for(let j=0;j<cands.length;j++){const c=cands[j];if(used[j]||c.axis!==seed.axis)continue;if(c.coord<lo-1||c.coord>hi+1)continue;if(Math.max(hi,c.coord)-Math.min(lo,c.coord)+1>maxT)continue;if(overlap(ga,gb,c.a,c.b)>=.72){g.push(c);used[j]=true;changed=true}}}const cs=g.map(x=>x.coord);out.push({axis:seed.axis,coord:cs.reduce((a,b)=>a+b,0)/cs.length,a:Math.min(...g.map(x=>x.a)),b:Math.max(...g.map(x=>x.b)),thick:new Set(cs).size})}return out}
function normalizeRegion(r,w,h){if(!r)return{x:0,y:0,width:w,height:h};const x=clamp(Math.round(r.x),0,w-1),y=clamp(Math.round(r.y),0,h-1);return{x,y,width:Math.max(1,Math.min(Math.round(r.width),w-x)),height:Math.max(1,Math.min(Math.round(r.height),h-y))}}
function makeFrame(region,mpp){return{anchor_px:{x:region.x,y:region.y},anchor_world_m:{x:0,y:0},meters_per_pixel:mpp,rotation_deg:0,image_y_axis:'down'}}
function sourcePxToWorld(f,p){const a=(f.rotation_deg||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),dx=(p.x-f.anchor_px.x)*f.meters_per_pixel,dy=(p.y-f.anchor_px.y)*f.meters_per_pixel*(f.image_y_axis==='up'?-1:1);return{x:f.anchor_world_m.x+dx*ca-dy*sa,y:f.anchor_world_m.y+dx*sa+dy*ca}}
function worldToSourcePx(f,p){let dx=p.x-f.anchor_world_m.x,dy=p.y-f.anchor_world_m.y,a=-(f.rotation_deg||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),rx=dx*ca-dy*sa,ry=dx*sa+dy*ca;if(f.image_y_axis==='up')ry=-ry;return{x:f.anchor_px.x+rx/f.meters_per_pixel,y:f.anchor_px.y+ry/f.meters_per_pixel}}
function createScaleCalibration(p1,p2,knownLengthM,method='manual_reference'){const px=Math.hypot(p2.x-p1.x,p2.y-p1.y),m=Number(knownLengthM);if(!(px>1&&m>0))throw new Error('比例校正需要有效的線段與實際長度');return{method,source_start_px:{...p1},source_end_px:{...p2},pixel_length:px,real_length_m:m,meters_per_pixel:m/px}}
function analyzeImageData(imageData,opts={}){const W=imageData.width,H=imageData.height,mpp=Number(opts.meters_per_pixel||opts.scale_calibration?.meters_per_pixel||.02);if(!(mpp>0))throw new Error('meters_per_pixel 必須 > 0');const threshold=clamp(Number(opts.threshold??128),0,255),minLen=clamp(Number(opts.min_wall_length_px||16),2,5000),maxT=clamp(Number(opts.max_wall_thickness_px||16),1,128),height=Math.max(.1,Number(opts.wall_height_m||2.7)),defaultThickness=Math.max(.01,Number(opts.wall_thickness_m||.12)),region=normalizeRegion(opts.analysis_region_px,W,H),frame=makeFrame(region,mpp),dark=Array.from({length:region.height},()=>new Uint8Array(region.width)),data=imageData.data;for(let y=0;y<region.height;y++)for(let x=0;x<region.width;x++){const sx=region.x+x,sy=region.y+y,i=(sy*W+sx)*4,gray=Math.round(.299*data[i]+.587*data[i+1]+.114*data[i+2]);dark[y][x]=gray<=threshold?1:0}const c=[];for(let y=0;y<region.height;y++)for(const[a,b]of runs(Array.from(dark[y],Boolean),minLen))c.push({axis:'h',coord:y,a,b});for(let x=0;x<region.width;x++){const col=new Array(region.height);for(let y=0;y<region.height;y++)col[y]=!!dark[y][x];for(const[a,b]of runs(col,minLen))c.push({axis:'v',coord:x,a,b})}const walls=collapse(c,maxT).map((r,n)=>{const s=r.axis==='h'?{x:region.x+r.a,y:region.y+r.coord}:{x:region.x+r.coord,y:region.y+r.a},e=r.axis==='h'?{x:region.x+r.b,y:region.y+r.coord}:{x:region.x+r.coord,y:region.y+r.b};return{id:`wall-${String(n+1).padStart(4,'0')}`,start:sourcePxToWorld(frame,s),end:sourcePxToWorld(frame,e),thickness:r.thick>1?Math.max(defaultThickness,r.thick*mpp):defaultThickness,height,confidence:1,source:'auto'}});return{version:'0.5',units:'m',image_width_px:W,image_height_px:H,meters_per_pixel:mpp,coordinate_frame:frame,analysis_region_px:region,scale_calibration:opts.scale_calibration||null,detection:{threshold,min_wall_length_px:minLen,max_wall_thickness_px:maxT},geometry:{wall_height_m:height,wall_thickness_m:defaultThickness,floor_enabled:opts.floor_enabled!==false,floor_thickness_m:Math.max(.01,Number(opts.floor_thickness_m||.15))},walls,edits:[],_debug:{dark}}}
function nextId(ir){ir._manual_seq=(ir._manual_seq||0)+1;return`wall-manual-${String(ir._manual_seq).padStart(4,'0')}`}
function addWallPx(ir,aPx,bPx,opts={}){const out=clone(ir);let a={...aPx},b={...bPx};if(opts.orthogonal!==false){if(Math.abs(b.x-a.x)>=Math.abs(b.y-a.y))b.y=a.y;else b.x=a.x}if(Math.hypot(b.x-a.x,b.y-a.y)<3)return out;const wall={id:nextId(out),start:sourcePxToWorld(out.coordinate_frame,a),end:sourcePxToWorld(out.coordinate_frame,b),thickness:Math.max(.01,Number(opts.thickness_m||out.geometry?.wall_thickness_m||.12)),height:Math.max(.1,Number(opts.height_m||out.geometry?.wall_height_m||2.7)),confidence:1,source:'manual'};out.walls.push(wall);(out.edits||(out.edits=[])).push({op:'add_wall',wall_id:wall.id,start_px:a,end_px:b});return out}
function pointSeg(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,l2=vx*vx+vy*vy;if(!l2)return{distance:Math.hypot(p.x-a.x,p.y-a.y),t:0};const t=clamp(((p.x-a.x)*vx+(p.y-a.y)*vy)/l2,0,1),q={x:a.x+t*vx,y:a.y+t*vy};return{distance:Math.hypot(p.x-q.x,p.y-q.y),t}}
function mergeIntervals(xs){if(!xs.length)return[];xs.sort((a,b)=>a[0]-b[0]);const out=[xs[0].slice()];for(let i=1;i<xs.length;i++){const c=xs[i],l=out[out.length-1];if(c[0]<=l[1])l[1]=Math.max(l[1],c[1]);else out.push(c.slice())}return out}
function eraseStrokePx(ir,points,radiusPx=10){const out=clone(ir),newWalls=[],targets=[];for(const wall of out.walls){const a=worldToSourcePx(out.coordinate_frame,wall.start),b=worldToSourcePx(out.coordinate_frame,wall.end),len=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),ints=[];for(const p of points){const hit=pointSeg(p,a,b);if(hit.distance<=radiusPx){const dt=radiusPx/len;ints.push([clamp(hit.t-dt,0,1),clamp(hit.t+dt,0,1)])}}if(!ints.length){newWalls.push(wall);continue}const erased=mergeIntervals(ints);targets.push({wall_id:wall.id,intervals:erased});const keep=[];let cur=0;for(const[e0,e1]of erased){if(e0>cur)keep.push([cur,e0]);cur=Math.max(cur,e1)}if(cur<1)keep.push([cur,1]);let part=0;for(const[k0,k1]of keep){if(k1-k0<.005)continue;part++;const p0={x:a.x+(b.x-a.x)*k0,y:a.y+(b.y-a.y)*k0},p1={x:a.x+(b.x-a.x)*k1,y:a.y+(b.y-a.y)*k1};newWalls.push({...wall,id:`${wall.id}-s${part}`,start:sourcePxToWorld(out.coordinate_frame,p0),end:sourcePxToWorld(out.coordinate_frame,p1)})}}out.walls=newWalls;if(targets.length)(out.edits||(out.edits=[])).push({op:'erase_segments',radius_px:radiusPx,targets});return out}
function setGeometry(ir,opts={}){const out=clone(ir),g=out.geometry||(out.geometry={});if(opts.wall_height_m!=null)g.wall_height_m=Math.max(.1,Number(opts.wall_height_m));if(opts.wall_thickness_m!=null)g.wall_thickness_m=Math.max(.01,Number(opts.wall_thickness_m));if(opts.floor_enabled!=null)g.floor_enabled=!!opts.floor_enabled;if(opts.floor_thickness_m!=null)g.floor_thickness_m=Math.max(.01,Number(opts.floor_thickness_m));out.walls=out.walls.map(w=>({...w,height:g.wall_height_m??w.height,thickness:g.wall_thickness_m??w.thickness}));(out.edits||(out.edits=[])).push({op:'set_geometry',geometry:clone(g)});return out}
function stripDebug(ir){const c=clone(ir);delete c._debug;delete c._manual_seq;return c}
function assertRoundTrip(ir,eps=1e-6){for(const w of ir.walls)for(const p of [w.start,w.end]){const px=worldToSourcePx(ir.coordinate_frame,p),p2=sourcePxToWorld(ir.coordinate_frame,px);if(Math.abs(p.x-p2.x)>eps||Math.abs(p.y-p2.y)>eps)throw new Error('coordinate frame round-trip invariant failed')}return true}
global.LayoutLibBrowser={version:'0.5.0',analyzeImageData,sourcePxToWorld,worldToSourcePx,createScaleCalibration,addWallPx,eraseStrokePx,setGeometry,stripDebug,assertRoundTrip};
})(window);
