/* LayoutLib Browser Adapter v0.6.0
 * Raster -> editable Spatial IR with generalized LayoutProfileLearner.
 * Learns accepted parser parameters from visual/structural features, not image identity.
 */
(function(global){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), clone=v=>JSON.parse(JSON.stringify(v));
function runs(bits,minLen){const out=[];let s=null;for(let i=0;i<=bits.length;i++){const on=i<bits.length?bits[i]:false;if(on&&s===null)s=i;else if(!on&&s!==null){if(i-s>=minLen)out.push([s,i-1]);s=null}}return out}
function overlap(a0,a1,b0,b1){const inter=Math.max(0,Math.min(a1,b1)-Math.max(a0,b0)+1),den=Math.max(1,Math.min(a1-a0+1,b1-b0+1));return inter/den}
function collapse(cands,maxT){const used=new Array(cands.length).fill(false),out=[];for(let i=0;i<cands.length;i++){if(used[i])continue;const seed=cands[i],g=[seed];used[i]=true;let changed=true;while(changed){changed=false;const cs=g.map(x=>x.coord),lo=Math.min(...cs),hi=Math.max(...cs),ga=Math.min(...g.map(x=>x.a)),gb=Math.max(...g.map(x=>x.b));for(let j=0;j<cands.length;j++){const c=cands[j];if(used[j]||c.axis!==seed.axis)continue;if(c.coord<lo-1||c.coord>hi+1)continue;if(Math.max(hi,c.coord)-Math.min(lo,c.coord)+1>maxT)continue;if(overlap(ga,gb,c.a,c.b)>=.72){g.push(c);used[j]=true;changed=true}}}const cs=g.map(x=>x.coord);out.push({axis:seed.axis,coord:cs.reduce((a,b)=>a+b,0)/cs.length,a:Math.min(...g.map(x=>x.a)),b:Math.max(...g.map(x=>x.b)),thick:new Set(cs).size})}return out}
function normalizeRegion(r,w,h){if(!r)return{x:0,y:0,width:w,height:h};const x=clamp(Math.round(r.x),0,w-1),y=clamp(Math.round(r.y),0,h-1);return{x,y,width:Math.max(1,Math.min(Math.round(r.width),w-x)),height:Math.max(1,Math.min(Math.round(r.height),h-y))}}
function makeFrame(region,mpp){return{anchor_px:{x:region.x,y:region.y},anchor_world_m:{x:0,y:0},meters_per_pixel:mpp,rotation_deg:0,image_y_axis:'down'}}
function sourcePxToWorld(f,p){const a=(f.rotation_deg||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),dx=(p.x-f.anchor_px.x)*f.meters_per_pixel,dy=(p.y-f.anchor_px.y)*f.meters_per_pixel*(f.image_y_axis==='up'?-1:1);return{x:f.anchor_world_m.x+dx*ca-dy*sa,y:f.anchor_world_m.y+dx*sa+dy*ca}}
function worldToSourcePx(f,p){let dx=p.x-f.anchor_world_m.x,dy=p.y-f.anchor_world_m.y,a=-(f.rotation_deg||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),rx=dx*ca-dy*sa,ry=dx*sa+dy*ca;if(f.image_y_axis==='up')ry=-ry;return{x:f.anchor_px.x+rx/f.meters_per_pixel,y:f.anchor_px.y+ry/f.meters_per_pixel}}
function createScaleCalibration(p1,p2,knownLengthM,method='manual_reference'){const px=Math.hypot(p2.x-p1.x,p2.y-p1.y),m=Number(knownLengthM);if(!(px>1&&m>0))throw new Error('比例校正需要有效的線段與實際長度');return{method,source_start_px:{...p1},source_end_px:{...p2},pixel_length:px,real_length_m:m,meters_per_pixel:m/px}}
function analyzeImageData(imageData,opts={}){const W=imageData.width,H=imageData.height,mpp=Number(opts.scale_calibration?.meters_per_pixel||opts.meters_per_pixel||.02);if(!(mpp>0))throw new Error('meters_per_pixel 必須 > 0');const threshold=clamp(Number(opts.threshold??128),0,255),minLen=clamp(Number(opts.min_wall_length_px||16),2,5000),maxT=clamp(Number(opts.max_wall_thickness_px||16),1,128),height=Math.max(.1,Number(opts.wall_height_m||2.7)),defaultThickness=Math.max(.01,Number(opts.wall_thickness_m||.12)),region=normalizeRegion(opts.analysis_region_px,W,H),frame=makeFrame(region,mpp),dark=Array.from({length:region.height},()=>new Uint8Array(region.width)),data=imageData.data;for(let y=0;y<region.height;y++)for(let x=0;x<region.width;x++){const sx=region.x+x,sy=region.y+y,i=(sy*W+sx)*4,gray=Math.round(.299*data[i]+.587*data[i+1]+.114*data[i+2]);dark[y][x]=gray<=threshold?1:0}const c=[];for(let y=0;y<region.height;y++)for(const[a,b]of runs(Array.from(dark[y],Boolean),minLen))c.push({axis:'h',coord:y,a,b});for(let x=0;x<region.width;x++){const col=new Array(region.height);for(let y=0;y<region.height;y++)col[y]=!!dark[y][x];for(const[a,b]of runs(col,minLen))c.push({axis:'v',coord:x,a,b})}const walls=collapse(c,maxT).map((r,n)=>{const s=r.axis==='h'?{x:region.x+r.a,y:region.y+r.coord}:{x:region.x+r.coord,y:region.y+r.a},e=r.axis==='h'?{x:region.x+r.b,y:region.y+r.coord}:{x:region.x+r.coord,y:region.y+r.b};return{id:`wall-${String(n+1).padStart(4,'0')}`,start:sourcePxToWorld(frame,s),end:sourcePxToWorld(frame,e),thickness:r.thick>1?Math.max(defaultThickness,r.thick*mpp):defaultThickness,height,confidence:1,source:'auto'}});return{version:'0.6',units:'m',image_width_px:W,image_height_px:H,meters_per_pixel:mpp,coordinate_frame:frame,analysis_region_px:region,scale_calibration:opts.scale_calibration||null,detection:{threshold,min_wall_length_px:minLen,max_wall_thickness_px:maxT},geometry:{wall_height_m:height,wall_thickness_m:defaultThickness,floor_enabled:opts.floor_enabled!==false,floor_thickness_m:Math.max(.01,Number(opts.floor_thickness_m||.15))},walls,edits:[],profile_prediction:opts.profile_prediction||null,_debug:{dark}}}
function nextId(ir){ir._manual_seq=(ir._manual_seq||0)+1;return`wall-manual-${String(ir._manual_seq).padStart(4,'0')}`}
function addWallPx(ir,aPx,bPx,opts={}){const out=clone(ir);let a={...aPx},b={...bPx};if(opts.orthogonal!==false){if(Math.abs(b.x-a.x)>=Math.abs(b.y-a.y))b.y=a.y;else b.x=a.x}if(Math.hypot(b.x-a.x,b.y-a.y)<3)return out;const wall={id:nextId(out),start:sourcePxToWorld(out.coordinate_frame,a),end:sourcePxToWorld(out.coordinate_frame,b),thickness:Math.max(.01,Number(opts.thickness_m||out.geometry?.wall_thickness_m||.12)),height:Math.max(.1,Number(opts.height_m||out.geometry?.wall_height_m||2.7)),confidence:1,source:'manual'};out.walls.push(wall);(out.edits||(out.edits=[])).push({op:'add_wall',wall_id:wall.id,start_px:a,end_px:b,orthogonal:opts.orthogonal!==false});return out}
function pointSeg(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,l2=vx*vx+vy*vy;if(!l2)return{distance:Math.hypot(p.x-a.x,p.y-a.y),t:0};const t=clamp(((p.x-a.x)*vx+(p.y-a.y)*vy)/l2,0,1),q={x:a.x+t*vx,y:a.y+t*vy};return{distance:Math.hypot(p.x-q.x,p.y-q.y),t}}
function mergeIntervals(xs){if(!xs.length)return[];xs.sort((a,b)=>a[0]-b[0]);const out=[xs[0].slice()];for(let i=1;i<xs.length;i++){const c=xs[i],l=out[out.length-1];if(c[0]<=l[1])l[1]=Math.max(l[1],c[1]);else out.push(c.slice())}return out}
function previewEraseStrokePx(ir,points,radiusPx=10){const targets=[];for(const wall of ir.walls){const a=worldToSourcePx(ir.coordinate_frame,wall.start),b=worldToSourcePx(ir.coordinate_frame,wall.end),len=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),ints=[];for(const p of points){const hit=pointSeg(p,a,b);if(hit.distance<=radiusPx){const dt=radiusPx/len;ints.push([clamp(hit.t-dt,0,1),clamp(hit.t+dt,0,1)])}}const intervals=mergeIntervals(ints);if(intervals.length)targets.push({wall_id:wall.id,a,b,intervals})}return{radius_px:radiusPx,targets}}
function eraseStrokePx(ir,points,radiusPx=10){const out=clone(ir),impact=previewEraseStrokePx(out,points,radiusPx),byId=new Map(impact.targets.map(x=>[x.wall_id,x])),newWalls=[];for(const wall of out.walls){const t=byId.get(wall.id);if(!t){newWalls.push(wall);continue}const{a,b,intervals}=t,keep=[];let cur=0;for(const[e0,e1]of intervals){if(e0>cur)keep.push([cur,e0]);cur=Math.max(cur,e1)}if(cur<1)keep.push([cur,1]);let part=0;for(const[k0,k1]of keep){if(k1-k0<.005)continue;part++;const p0={x:a.x+(b.x-a.x)*k0,y:a.y+(b.y-a.y)*k0},p1={x:a.x+(b.x-a.x)*k1,y:a.y+(b.y-a.y)*k1};newWalls.push({...wall,id:`${wall.id}-s${part}`,start:sourcePxToWorld(out.coordinate_frame,p0),end:sourcePxToWorld(out.coordinate_frame,p1)})}}out.walls=newWalls;if(impact.targets.length)(out.edits||(out.edits=[])).push({op:'erase_segments',radius_px:radiusPx,stroke_points:points.map(p=>({...p})),targets:impact.targets.map(t=>({wall_id:t.wall_id,intervals:t.intervals}))});return out}
function setGeometry(ir,opts={}){const out=clone(ir),g=out.geometry||(out.geometry={});if(opts.wall_height_m!=null)g.wall_height_m=Math.max(.1,Number(opts.wall_height_m));if(opts.wall_thickness_m!=null)g.wall_thickness_m=Math.max(.01,Number(opts.wall_thickness_m));if(opts.floor_enabled!=null)g.floor_enabled=!!opts.floor_enabled;if(opts.floor_thickness_m!=null)g.floor_thickness_m=Math.max(.01,Number(opts.floor_thickness_m));out.walls=out.walls.map(w=>({...w,height:g.wall_height_m??w.height,thickness:g.wall_thickness_m??w.thickness}));(out.edits||(out.edits=[])).push({op:'set_geometry',geometry:clone(g)});return out}
function replayEdits(base,edits=[]){let out=clone(base);for(const e of edits){if(e.op==='add_wall'&&e.start_px&&e.end_px)out=addWallPx(out,e.start_px,e.end_px,{orthogonal:e.orthogonal!==false});else if(e.op==='erase_segments'&&e.stroke_points)out=eraseStrokePx(out,e.stroke_points,e.radius_px||10)}return out}
function stripDebug(ir){const c=clone(ir);delete c._debug;delete c._manual_seq;return c}
function assertRoundTrip(ir,eps=1e-6){for(const w of ir.walls)for(const p of [w.start,w.end]){const px=worldToSourcePx(ir.coordinate_frame,p),p2=sourcePxToWorld(ir.coordinate_frame,px);if(Math.abs(p.x-p2.x)>eps||Math.abs(p.y-p2.y)>eps)throw new Error('coordinate frame round-trip invariant failed')}return true}

// --- Generalized profile learning -------------------------------------------------
const FEATURE_KEYS=['background_luma','contrast','dark_ratio','edge_density','horizontal_edge_ratio','vertical_edge_ratio','ink_spread'];
function extractProfileFeatures(imageData){const W=imageData.width,H=imageData.height,d=imageData.data,step=Math.max(1,Math.floor(Math.sqrt((W*H)/24000))),vals=[],hist=new Uint32Array(256);let dark=0,edges=0,hedges=0,vedges=0,total=0;const grayAt=(x,y)=>{const i=(y*W+x)*4;return Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2])};for(let y=0;y<H;y+=step)for(let x=0;x<W;x+=step){const g=grayAt(x,y);vals.push(g);hist[g]++;total++;if(g<160)dark++;if(x+step<W){const dx=Math.abs(g-grayAt(x+step,y));if(dx>28){edges++;vedges++}}if(y+step<H){const dy=Math.abs(g-grayAt(x,y+step));if(dy>28){edges++;hedges++}}}vals.sort((a,b)=>a-b);const q=p=>vals[Math.min(vals.length-1,Math.floor((vals.length-1)*p))]||0,q10=q(.1),q50=q(.5),q90=q(.9);let bgNum=0,bgDen=0;for(let i=180;i<256;i++){bgNum+=i*hist[i];bgDen+=hist[i]}const background=bgDen?bgNum/bgDen:q90,contrast=(q90-q10)/255,darkRatio=dark/Math.max(1,total),edgeDen=edges/Math.max(1,total*2),hRatio=hedges/Math.max(1,edges),vRatio=vedges/Math.max(1,edges),inkSpread=(q50-q10)/255;return{background_luma:+background.toFixed(3),contrast:+contrast.toFixed(5),dark_ratio:+darkRatio.toFixed(5),edge_density:+edgeDen.toFixed(5),horizontal_edge_ratio:+hRatio.toFixed(5),vertical_edge_ratio:+vRatio.toFixed(5),ink_spread:+inkSpread.toFixed(5),sample_step:step}}
const DEFAULT_RANGES={background_luma:70,contrast:.45,dark_ratio:.3,edge_density:.2,horizontal_edge_ratio:.5,vertical_edge_ratio:.5,ink_spread:.35};
function profileDistance(a,b){let sum=0,n=0;for(const k of FEATURE_KEYS){if(a[k]==null||b[k]==null)continue;const r=DEFAULT_RANGES[k]||1,d=(a[k]-b[k])/r;sum+=d*d;n++}return Math.sqrt(sum/Math.max(1,n))}
function predictProfileParameters(features,samples,opts={}){const valid=(samples||[]).filter(s=>s&&s.features&&Number.isFinite(Number(s.parameters?.threshold)));if(!valid.length)return{threshold:128,confidence:0,neighbors:0,source:'default'};const ranked=valid.map(s=>({s,d:profileDistance(features,s.features)})).sort((a,b)=>a.d-b.d),k=Math.min(Number(opts.k||5),ranked.length),near=ranked.slice(0,k);let sw=0,st=0,sm=0;for(const n of near){const w=1/Math.max(.04,n.d*n.d);sw+=w;st+=w*Number(n.s.parameters.threshold);sm+=w*Number(n.s.parameters.min_wall_length_px||16)}const nearest=near[0].d,diversity=Math.min(1,Math.log2(valid.length+1)/4),similarity=Math.exp(-nearest*2.2),confidence=clamp(similarity*(.35+.65*diversity),0,1);return{threshold:Math.round(clamp(st/sw,0,255)),min_wall_length_px:Math.round(clamp(sm/sw,2,5000)),confidence:+confidence.toFixed(3),neighbors:k,nearest_distance:+nearest.toFixed(4),source:'generalized_knn'}}
function makeLearningObservation(features,parameters,meta={}){return{schema:'layoutlib.profile-observation/v1',features:clone(features),parameters:{threshold:clamp(Number(parameters.threshold),0,255),min_wall_length_px:clamp(Number(parameters.min_wall_length_px||16),2,5000),max_wall_thickness_px:clamp(Number(parameters.max_wall_thickness_px||16),1,128)},accepted:true,created_at:new Date().toISOString(),meta:{...meta}}}
function compactLearningSamples(samples,max=200){const xs=(samples||[]).filter(Boolean);return xs.length<=max?xs:xs.slice(xs.length-max)}

global.LayoutLibBrowser={version:'0.6.0',analyzeImageData,sourcePxToWorld,worldToSourcePx,createScaleCalibration,addWallPx,previewEraseStrokePx,eraseStrokePx,setGeometry,replayEdits,stripDebug,assertRoundTrip,extractProfileFeatures,predictProfileParameters,makeLearningObservation,compactLearningSamples,profileDistance};
})(window);
