#!/usr/bin/env python3
from __future__ import annotations

import os
import re
from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(os.environ.get("AGENT_PROJECT_ROOT", Path(__file__).resolve().parents[1])).resolve()


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), os.path.expandvars(value.strip().strip('"').strip("'")))


load_env_file(PROJECT_ROOT / ".env")

AGENT_DATA_ROOT = Path(
    os.environ.get("AGENT_DATA_ROOT")
    or os.environ.get("AGENT_DATA_DIR")
    or Path.home() / "agent-data"
).expanduser()
KNOWLEDGE_ROOT = AGENT_DATA_ROOT / "knowledge"
SYSTEM_KNOWLEDGE_DIR = KNOWLEDGE_ROOT / "system"

SECRET_PATTERNS = [
    re.compile(r"(key=)[A-Za-z0-9_\-]{20,}", re.I),
    re.compile(r"(api[_-]?key\s*[:=]\s*)[A-Za-z0-9_\-]{12,}", re.I),
    re.compile(r"(token\s*[:=]\s*)[A-Za-z0-9_\-:.]{12,}", re.I),
    re.compile(r"AIza[0-9A-Za-z_\-]{20,}"),
]


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def read_text(path: Path, limit: int | None = None) -> str:
    if not path.exists():
        return ""
    content = path.read_text(encoding="utf-8", errors="replace")
    return content[-limit:] if limit else content


def sanitize(text: str) -> str:
    result = text
    for pattern in SECRET_PATTERNS:
        result = pattern.sub(lambda m: f"{m.group(1)}[REDACTED]" if m.groups() else "[REDACTED]", result)
    return result


def latest_file(folder: Path, pattern: str) -> Path | None:
    files = sorted(folder.glob(pattern), key=lambda p: p.stat().st_mtime if p.exists() else 0)
    return files[-1] if files else None


def extract_bullets(content: str, max_items: int = 10) -> list[str]:
    bullets: list[str] = []
    for raw_line in sanitize(content).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith(("- ", "* ", "> **", "### ", "## ")):
            compact = re.sub(r"\s+", " ", line)
            if len(compact) > 220:
                compact = compact[:217] + "..."
            if compact not in bullets:
                bullets.append(compact)
        if len(bullets) >= max_items:
            break
    return bullets


def build_operational_item() -> tuple[Path, str]:
    today = utc_now().strftime("%Y-%m-%d")
    latest_meditation = latest_file(AGENT_DATA_ROOT / "journals" / "meditation", "*.md")
    latest_report = latest_file(AGENT_DATA_ROOT / "journals" / "ecosystem_reports", "*.md")
    chronicle_path = AGENT_DATA_ROOT / "CHRONICLE.md"
    sync_path = AGENT_DATA_ROOT / "memory" / "session_sync.md"

    meditation = read_text(latest_meditation, 8000) if latest_meditation else ""
    report = read_text(latest_report, 8000) if latest_report else ""
    chronicle = read_text(chronicle_path, 8000)
    sync_tail = read_text(sync_path, 8000)

    health_lines = []
    barrier = re.search(r"Barrier Sync\*\*:\s*`([^`]+)`", report)
    if barrier:
        health_lines.append(f"- Barrier Sync: `{barrier.group(1)}`")
    memory = re.search(r"\*\*Memory\*\*:\s*(.+)", report)
    if memory:
        health_lines.append(f"- Memory: {sanitize(memory.group(1)).strip()}")
    if "SELF-REFLECTION FAILED" in meditation:
        health_lines.append("- Meditation: latest reflection recorded a model/API availability failure.")
    elif meditation:
        health_lines.append("- Meditation: latest daily reflection completed.")
    if not health_lines:
        health_lines.append("- No recent ecosystem report was available.")

    source_lines = [
        f"- Meditation: `{latest_meditation}`" if latest_meditation else "- Meditation: unavailable",
        f"- Ecosystem report: `{latest_report}`" if latest_report else "- Ecosystem report: unavailable",
        f"- Chronicle: `{chronicle_path}`",
        f"- Session sync tail: `{sync_path}`",
    ]

    content = [
        "---",
        "title: AgentOS Operational State",
        "category: system",
        "tags: [agentos, operations, memory, chronicle]",
        f"last_updated: {today}",
        "---",
        "",
        "# AgentOS Operational State",
        "",
        "This knowledge item is generated by `scripts/internalize.py` from the memory palace, daily meditation, ecosystem reports, and Chronicle.",
        "",
        "## Current Health",
        *health_lines,
        "",
        "## Recent Signals",
        *extract_bullets(report, 8),
        "",
        "## Memory Palace Signals",
        *extract_bullets(sync_tail, 8),
        "",
        "## Chronicle Signals",
        *extract_bullets(chronicle, 8),
        "",
        "## Sources",
        *source_lines,
        "",
        f"_Generated: {utc_now().strftime('%Y-%m-%d %H:%M:%S UTC')}_",
        "",
    ]

    target = SYSTEM_KNOWLEDGE_DIR / "AgentOS_Operational_State.md"
    return target, "\n".join(content)


def ensure_index_link(path: Path, link_text: str) -> bool:
    if not path.exists():
        return False
    content = path.read_text(encoding="utf-8")
    if link_text in content:
        return False
    marker = "## 🏗️ LAYER 1: System Infrastructure & Architecture"
    line = f"- **[[AgentOS_Operational_State]]**: Latest generated operational memory and Chronicle synthesis."
    if marker in content:
        content = content.replace(marker, f"{marker}\n{line}", 1)
    else:
        content += f"\n{line}\n"
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    SYSTEM_KNOWLEDGE_DIR.mkdir(parents=True, exist_ok=True)
    target, content = build_operational_item()
    target.write_text(content, encoding="utf-8")

    master_updated = ensure_index_link(
        KNOWLEDGE_ROOT / "Knowledge_Master_MOC.md",
        "[[AgentOS_Operational_State]]",
    )

    print(f"✅ Internalized operational knowledge: {target}")
    if master_updated:
        print("✅ Updated Knowledge_Master_MOC.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

