#!/usr/bin/env python3
import os
from pathlib import Path
import re
from datetime import datetime

# Dynamic Path Discovery (v0.6.2)
SCRIPT_DIR = Path(__file__).resolve().parent
LOGIC_ROOT = SCRIPT_DIR.parent
DATA_ROOT = (LOGIC_ROOT.parent / "agent-data")

if not DATA_ROOT.exists():
    # Fallback to home if not sibling
    DATA_ROOT = Path.home() / "agent-data"

SNAPSHOTS_DIR = DATA_ROOT / "memory/snapshots"
CHRONICLE_FILE = DATA_ROOT / "CHRONICLE.md"

KEYWORDS = [
    "v0.5.1",
    "繼承",
    "Inheritance",
    "LCS-Signal",
    "PM2",
    "Vaultwarden",
    "n8n",
    "AgentOS",
    "Architecture",
    "Watchdog",
    "Bootstrap",
    "Knowledge",
    "STATUS",
]


SECRET_PATTERNS = [
    re.compile(r"(key=)[A-Za-z0-9_\-]{20,}", re.I),
    re.compile(r"(api[_-]?key\s*[:=]\s*)[A-Za-z0-9_\-]{12,}", re.I),
    re.compile(r"(token\s*[:=]\s*)[A-Za-z0-9_\-:.]{12,}", re.I),
    re.compile(r"AIza[0-9A-Za-z_\-]{20,}"),
]


def sanitize(text: str) -> str:
    result = text
    for pattern in SECRET_PATTERNS:
        result = pattern.sub(lambda m: f"{m.group(1)}[REDACTED]" if m.groups() else "[REDACTED]", result)
    return result


def extract_snapshot_date(path: Path) -> str:
    match = re.search(r"(\d{4}-\d{2}-\d{2})", path.name)
    return match.group(1) if match else "unknown-date"


def high_signal_lines(content: str, limit: int = 18) -> list[str]:
    lines: list[str] = []
    for raw_line in sanitize(content).splitlines():
        line = raw_line.strip()
        if not line:
            continue
        important = (
            line.startswith("#")
            or line.startswith("- **")
            or line.startswith("- `")
            or line.startswith("- [")
            or any(kw.lower() in line.lower() for kw in KEYWORDS)
        )
        if not important:
            continue
        compact = re.sub(r"\s+", " ", line)
        if len(compact) > 240:
            compact = compact[:237] + "..."
        if compact not in lines:
            lines.append(compact)
        if len(lines) >= limit:
            break
    return lines

def recall():
    print(f"🌅 [Recall Protocol] Searching for truths in: {DATA_ROOT}")
    if not DATA_ROOT.exists():
        print(f"❌ Data Layer NOT FOUND at: {DATA_ROOT}")
        return

    history = []
    if not SNAPSHOTS_DIR.exists():
        print(f"❌ No snapshots found in: {SNAPSHOTS_DIR}")
        return

    snapshot_files = sorted(SNAPSHOTS_DIR.glob("*.md"), reverse=True)
    for sf in snapshot_files:
        content = sf.read_text(encoding="utf-8", errors="replace")
        signals = high_signal_lines(content)
        if signals:
            date = extract_snapshot_date(sf)
            mtime = datetime.utcfromtimestamp(sf.stat().st_mtime).strftime("%Y-%m-%d %H:%M UTC")
            entry = [
                f"## {date} — Snapshot `{sf.name}`",
                f"- **Generated/Modified**: {mtime}",
                f"- **Source Size**: {sf.stat().st_size / 1024:.1f} KB",
                "",
                "### High-Signal Events",
                *[f"- {line.lstrip('# ').strip()}" for line in signals],
            ]
            history.append("\n".join(entry))

    with open(CHRONICLE_FILE, "w", encoding="utf-8") as f:
        f.write("# AgentOS Historical Chronicle (v3)\n")
        f.write(f"> Generated by `recall_chronicle.py`. Data root: `{DATA_ROOT}`\n\n")
        if history:
            f.write("\n\n".join(history))
        else:
            f.write("- No high-signal snapshot entries found.\n")
        
    print(f"✅ Chronicle updated: {CHRONICLE_FILE}")

if __name__ == '__main__':
    recall()
