"""
agent_memory/handover.py
Formal session handover protocol for Agent OS.

This replaces scripts/handover.py (67-line append-only version).
The new handover protocol:
  1. Generates a structured next_agent_brief
  2. Writes a per-session YAML record (via session_store)
  3. Appends a COMPACT summary to session_sync.md (not a full dump)
  4. Emits a session_closed event
  5. Updates project.yaml health fields

The old session_sync.md bloat problem is addressed by:
  - Only writing 10-15 lines per handover (not hundreds)
  - Keeping full detail in the per-session YAML
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from agent_core.config import (
    CENTRAL_PROJECTS_DIR,
    MEMORY_DIR,
)


# Max lines to keep in a single handover entry in session_sync.md
_COMPACT_HANDOVER_MAX_LINES = 15
# If session_sync.md exceeds this, warn
_SYNC_MD_WARN_BYTES = 50 * 1024  # 50KB


def generate_brief(
    project_id: str,
    agent_id: str,
    summary: str,
    tasks_completed: list[str],
    tasks_blocked: list[str],
    pending_tasks: list[str],
    files_touched: list[str],
    context_notes: str = "",
) -> str:
    """
    Generate a structured next_agent_brief string.
    This is what the NEXT agent reads when they /work-on this project.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"## Agent Handover Brief — {project_id}",
        f"_Generated by `{agent_id}` @ {now}_",
        "",
        f"**Summary:** {summary or 'No summary provided.'}",
        "",
    ]

    if tasks_completed:
        lines.append("**✅ Completed this session:**")
        for t in tasks_completed[:5]:
            lines.append(f"  - {t}")
        lines.append("")

    if tasks_blocked:
        lines.append("**🚧 Blocked:**")
        for t in tasks_blocked[:3]:
            lines.append(f"  - {t}")
        lines.append("")

    if pending_tasks:
        lines.append("**📋 Next agent should tackle:**")
        for t in pending_tasks[:5]:
            lines.append(f"  - [ ] {t}")
        lines.append("")

    if files_touched:
        lines.append(f"**📁 Files touched:** `{'`, `'.join(files_touched[:5])}`")
        lines.append("")

    if context_notes:
        lines.append(f"**📝 Context:** {context_notes}")
        lines.append("")

    return "\n".join(lines)


def append_compact_to_sync(
    project_id: str,
    agent_id: str,
    session_id: str,
    summary: str,
    pending_tasks: list[str],
    next_agent_brief: str,
) -> Optional[Path]:
    """
    Append a compact (≤15 line) handover entry to session_sync.md.
    If the file is getting large, emit a warning but still write.
    """
    sync_path = MEMORY_DIR / "session_sync.md"

    # Warn if file is getting large
    warnings = []
    if sync_path.exists() and sync_path.stat().st_size > _SYNC_MD_WARN_BYTES:
        size_kb = sync_path.stat().st_size // 1024
        warnings.append(
            f"session_sync.md is {size_kb}KB — consider archiving. "
            f"Run: python3 scripts/compact_sync.py"
        )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build compact entry (≤_COMPACT_HANDOVER_MAX_LINES lines)
    top_tasks = pending_tasks[:3]
    task_str = " | ".join(f"`{t[:40]}`" for t in top_tasks) if top_tasks else "None"

    entry_lines = [
        f"\n---",
        f"**[{now}] Handover: `{project_id}`** by `{agent_id}` (`{session_id[:8]}…`)",
        f"> {summary[:200] if summary else '(no summary)'}",
        f"> **Pending:** {task_str}",
        f"> **→ Details:** `agent-data/projects/{project_id}/sessions/`",
        "",
    ]

    with open(sync_path, "a", encoding="utf-8") as f:
        f.write("\n".join(entry_lines))

    return sync_path


def extract_pending_from_markdown(memory_path: Path) -> list[str]:
    """
    Extract unchecked tasks from a SHORT_TERM.md or similar markdown file.
    Looks for '- [ ]' checkboxes.
    """
    if not memory_path.exists():
        return []

    tasks = []
    in_tasks_section = False
    for line in memory_path.read_text(encoding="utf-8").splitlines():
        # Detect task sections
        if re.match(r"#+\s*(🚧|Pending|近期任務|Tasks|TODO)", line):
            in_tasks_section = True
            continue
        # Exit task section on new header
        if in_tasks_section and line.startswith("#"):
            in_tasks_section = False
        # Collect unchecked items
        stripped = line.strip()
        if stripped.startswith("- [ ]"):
            tasks.append(stripped[6:].strip())

    return tasks


def archive_sync_if_needed(force: bool = False) -> Optional[Path]:
    """
    If session_sync.md exceeds 50KB (or force=True), archive it.
    Keeps last 500 lines in-place, moves old content to memory/archive/.
    Returns the archive path if archiving was done, else None.
    """
    sync_path = MEMORY_DIR / "session_sync.md"
    if not sync_path.exists():
        return None

    size = sync_path.stat().st_size
    if not force and size <= _SYNC_MD_WARN_BYTES:
        return None

    archive_dir = MEMORY_DIR / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M")
    archive_path = archive_dir / f"session_sync_{stamp}.md"

    content = sync_path.read_text(encoding="utf-8")
    lines = content.splitlines()

    # Keep last 500 lines, archive the rest
    keep_lines = lines[-500:]
    archive_content = "\n".join(lines[:-500])

    archive_path.write_text(archive_content, encoding="utf-8")
    sync_path.write_text("\n".join(keep_lines), encoding="utf-8")

    return archive_path
